### ISSUE TITLE
conflict with mods AAI Industry and space exploration postprocess 

### ISSUE THREAD

**Issue by YesYatta** [grandseiken/factorio-ultracube#23]
When launching Factorio with the Ultracube, AAI Industry and space exploration mods it gives an error
![Снимок](https://github.com/grandseiken/factorio-ultracube/assets/149840883/68677af6-7bbe-4bfb-843b-34e62d66e62f)

**Comment by grandseiken** [comment]
Why are you launching it with space exploration? That isn't going to work, they're completely incompatible.
