### ISSUE TITLE
Ziggurat construction research voids tech cards

### ISSUE THREAD

**Issue by TheRamenChef** [grandseiken/factorio-ultracube#27]
It appears that having the "clandestine construction project" research selected will instantly delete any tech cards that enter your labs. Not sequence-breaking, but in the time I took to notice it was happening I lost quite a lot of resources.

**Comment by grandseiken** [comment]
I'll have a look at whether this is something that I can actually fix (it might not be).

**Comment by grandseiken** [comment]
In 2.0 this now used the built-in trigger technology system.
