### ISSUE TITLE
Soft Error caused by Steam Boiler

### ISSUE THREAD

**Issue by IhaveSwordz** [grandseiken/factorio-ultracube#30]
With any attempted interaction (hovering, hovering to craft, picking up to place, hovering while placed, etc...) the game freezes for ~ 4 seconds. Once the game is done after that, if still attempting interaction (ie in you hand) then it freezes again. To try and fix this I:
reinstalled mod
verified factorio integrity
updated and restarted my windows 10 instillation

None of this worked, so I went and explored the factorio-current.log file and found a stack trace as follows:

1368.889 Error RuntimeError.cpp:24: Missing specification of sprite with name: "tooltip-category-burnable-fuel"
Factorio crashed. Generating symbolized stacktrace, please wait ...
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\libraries\StackWalker\StackWalker.cpp (924): StackWalker::ShowCallstack
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\Util\Logger.cpp (339): Logger::writeStacktrace
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\Util\Logger.cpp (346): Logger::logStacktrace
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\libraries\CommonUtil\Exceptions.cpp (9): InputException::InputException
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\SpriteBank.cpp (209): SpriteBank::getSprite
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\SpriteBank.cpp (279): SpriteBank::isSpritePathValid
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\Util\PropertyCategory.cpp (31): PropertyCategory::getIconName
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\Util\Description.cpp (289): Description::fillCategory
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\Util\Description.cpp (158): Description::fill
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\Gui\ElemToolTip.cpp (91): ElemToolTip<ID<ItemPrototype,unsigned short>,ItemStack>::updateContent
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\libraries\Agui\Widget\Widget.cpp (816): agui::Widget::mouseHover
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\libraries\Agui\Gui.cpp (509): agui::Gui::handleHover
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\libraries\Agui\Gui.cpp (819): agui::Gui::logic
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\GlobalContext.cpp (1498): GlobalContext::updateGui
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\MainLoop.cpp (1147): MainLoop::prepare
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\MainLoop.cpp (717): MainLoop::mainLoopStep
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\MainLoop.cpp (423): MainLoop::run
C:\Users\build\AppData\Local\Temp\factorio-build-M81HuB\src\Main.cpp (1277): wmain
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl (288): __scrt_common_main_seh
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF8F9A17344)
00007FF8F9A17344 (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF8FA3426B1)
00007FF8FA3426B1 (ntdll): (filename not available): RtlUserThreadStart
Stack trace logging done

from my brief read it appears there is some issue with the gui associated with the mod's implementation of the boiler.
here is the log file.
[factorio-current.log](https://github.com/grandseiken/factorio-ultracube/files/15343112/factorio-current.log)
here is my save.
[ultracube.zip](https://github.com/grandseiken/factorio-ultracube/files/15343128/ultracube.zip)

I am unsure what is different about my game that would cause this error, but it is very easy for me to personally reproduce, and it makes the mod practically unplayable.

**Comment by grandseiken** [comment]
Hey, unfortunately this looks like a problem with your game installation or some other mod, I don't think it has much to do with ultracube. I would try reinstalling factorio and/or disabling other mods.

**Comment by grandseiken** [comment]
(I can load your save and it works just fine, by the way.)

**Comment by IhaveSwordz** [comment]
I just got a new computer, and only porting the world and reinstalling the mods worked fine. Porting over other stuff like config and related made it break.

**Comment by grandseiken** [comment]
Resolved then?
