### ISSUE TITLE
Crash when hovering over locomotive

### ISSUE THREAD

**Issue by MyNameIsTrez** [grandseiken/factorio-ultracube#6]
Hello! I've been enjoying your mod tremendously, I don't think I've ever had a mod make me think deep, and need to really use circuit networks before for an efficient base. I have my base automatically creating Abstract interrogation cards, but because my base is using only one machine per Ultracube recipe right now, I am planning to make a new base. :-)

When you hover over the locomotive in this save, the game crashes after a moment for me:
[Ultracube train crash.zip](https://github.com/grandseiken/factorio-ultracube/files/13796457/Ultracube.train.crash.zip)

![image](https://github.com/grandseiken/factorio-ultracube/assets/32989873/79489c35-d1f5-4ea1-aea8-842a52e8c2d2)

This is the list of mods I am using. They are just the non-optional mods for your mod:
- AAI Loaders
- Base mod
- Krastorio 2 Assets
- Simulation Helper
- Ultracube: Age of Cube

**Comment by grandseiken** [comment]
Thanks for the detailed report with save, should make it easy to fix. I'll investigate this soon.

**Comment by grandseiken** [comment]
Hey, I haven't been able to reproduce the issue with the save on the latest version and I notice the screenshot you posted is 0.2.1. I believe this issue was already fixed so you should be able to sort it by updating the mod.

**Comment by MyNameIsTrez** [comment]
Can confirm it has been fixed :)
